### ISSUE TITLE
Missing citation of Godot RL Agents in Neurips paper

### ISSUE THREAD

**Issue by edbeeching** [Avalon-Benchmark/avalon#2]
Great work on this simulator.

In your custom env [readme](https://github.com/Avalon-Benchmark/avalon/tree/main/docs/tutorial_custom_env) you say "Our GodotEnv is similar in spirit to [Godot RL Agents](https://github.com/edbeeching/godot_rl_agents)".
I was wondering if you could add a citation of [our work](https://arxiv.org/abs/2112.03636) to the related works section of your paper?

**Comment by mx781** [comment]
Thanks! We didn't really use Godot RL Agents for the paper, and the link was meant more as a comparison for users to better decide if using the underlying GodotEnv is suitable for them. Our core contribution is ultimately around benchmarking RL generalization and less so the environment-building side of things, so adding a citation under related works doesn't seem pertinent to the paper, sorry.
