### ISSUE TITLE
License

### ISSUE THREAD

**Issue by timokau** [Avalon-Benchmark/avalon#5]
Hi,

thank you for your work on this, it looks great at first glance! I'm wondering what the license for the simulator and the baseline agents is. Could you clarify and maybe add a LICENSE file?

**Comment by mx781** [comment]
Hi @timokau, the license for the simulator as well as baseline agents is GPLv3, you can see the full license details on the [OpenReview page](https://openreview.net/forum?id=TzNuIdrHoU). We'll add a README section and probably a LICENSE file to make this more clear - thanks for the tip!

**Comment by timokau** [comment]
Thanks for clarifying!
